project:
  type: website

website:
  title: "Visual Communication and Data Storytelling"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: "https://github.com/{{< var org.name >}}"
        text: GitHub-Organization

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Syllabus"
        file: index.qmd
      - text: "**Schedule**"
        file: schedule.qmd
      - text: "Project: Milestones"
        file: milestones.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true

